# Generated by Django 5.0.4 on 2024-06-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='domain',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
